name: rl_kensyu
channels:
  - defaults
dependencies:
  - python==3.7.7
  - pip
  - pip:
    - ale-py==0.7.4
    - atari-py==0.2.5
    - ray
    - gym==0.18.3
    - stable-baselines==2.10.2
    - tensorflow==1.15.0
